### PR TITLE
Remove QueueListener test

### PR DESCRIPTION
**Pull request by aminalaee**
I think there's no issue with the QueueListener hut as explained it's a testing limitation with pytest caplog.
closes https://github.com/microsoft/picologging/issues/90

### CODE REVIEW

**Comment by Goldziher** [comment]
This is no way to test this - either adjust the test to make it pass, if you think it's faulty, or identify the issue.

I know for a fact this is not working because I tested it on my end, see the link. But even if that was not the case, simply removing the test without a clear assertion there is no issue (via working test), is imho wrong.

**Comment by aminalaee** [comment]
Well there was already a test for this that’s why I suggested to remove it.
https://github.com/microsoft/picologging/blob/762f49fb1af3139474ebade5a5d07b1fc04cdc82/tests/unit/test_queuehandler.py#L34

But if it’s different or I made a mistake we van close this.

**Comment by Goldziher** [comment]
@aminalaee --> https://github.com/microsoft/picologging/pull/102

**Comment by Goldziher** [comment]
> Well there was already a test for this that’s why I suggested to remove it.
> 
> https://github.com/microsoft/picologging/blob/762f49fb1af3139474ebade5a5d07b1fc04cdc82/tests/unit/test_queuehandler.py#L34
> 
> But if it’s different or I made a mistake we van close this.

that test only shows that the value is written to the stream. Yet the tests I added demonstrate that this is not written into the output captured by pytest. Something is not right - somewhere.

**Comment by aminalaee** [comment]
I don't think the tests you updated are the test.
In stdlib logging you sre writing stdout but in picologging test you are writing to a StringIO so you can't check caplog.

I might be wrong though, let's for the maintainers to review.

**Comment by Goldziher** [comment]
> I don't think the tests you updated are the same. In stdlib logging you are writing to stdout but in picologging test you are writing to a StringIO so you can't check caplog.
> 
> I might be wrong though, let's wait for the maintainers to review.

I simply used the example in the docs for the tests. In starlite I do not use the same code, and it still fails.

**Comment by pamelafox** [comment]
[Posting on both relevant PRs]
To keep our discussion in one place for now, let's keep discussing in https://github.com/microsoft/picologging/issues/90 and then figure out what code change to make.
Thank you!

**Comment by pamelafox** [comment]
This is fine to remove now since the test based on it is now checked in:
https://github.com/microsoft/picologging/pull/122/files#diff-9860c055bbe5b5def7a4f1ca7574748b0afad2904461493c41a631559f5fb97eR48

**Review by pamelafox — APPROVED** [review]

**Review by tonybaloney — APPROVED** [review]

**Pull request merged**
