### PR TITLE
Add tests for FileHandler delay

### PR DESCRIPTION
**Pull request by aminalaee**
Adding tests for `FileHandler` with the `delay` option and also fixing the case:
https://github.com/microsoft/picologging/blob/32b6a29a102feffba654b253d3b08cccef87555c/src/picologging/__init__.py#L404-L406
Since the `StreamHandler.__init__` has not been called and `StreamHandler.emit` is called, `terminator` and `_const_write` will be nullptr and it will fail here:
https://github.com/microsoft/picologging/blob/32b6a29a102feffba654b253d3b08cccef87555c/src/picologging/streamhandler.cxx#L56-L61

Not really sure if it will be useful if the `FileHandler` extension will be available later.

### CODE REVIEW

**Comment by tonybaloney** [comment]
I've thought about this a bit more. The way the standard library is invoking the parent methods is wrong (IMO). 

Please can you do the following:

1. Submit a PR with _only_ the test demonstrating the breakage.
2. Change the Python code to call `super()` using the modern Python 3 syntax, it shouldn't require any modifications to the C extension
3. Demonstrate the fixed test

**Comment by aminalaee** [comment]
@tonybaloney I added the failing test only (item 1) and tried calling `super().emit(record)` in `FileHandler` but that doesn't solve the issue.

The problem is that `StreamHandler.__init__` has not been called, therefore the variables `terminator` and `_const_write `  not set up.

We could also fix it in the Python code:

```python
class FileHandler(...):
    def emit(record):
        if self.stream is None:
            self.stream = self._open()
            StreamHandler.__init__(self, self.stream). # This can set it up
        super().emit(record)
```

But as you said it will be a an extra step, but maybe this is better as it won't interfere with each emit and only the first time.

**Comment by tonybaloney** [comment]
I think there are two bugs here:

1. There are code paths where FileHandler doesn't invoke the constructor of its parent class, which is wrong and leads to unexpected behaviours. This _should_ be done inside the initializer, not in other methods IMO
2. Some fields, e.g. the `_const_write_` and `terminator` may not be initialized and should be set inside `__new__` instead of `__init__` in the C extension type (this also solves most of 1)

**Comment by tonybaloney** [comment]
#28 will fix some of this behaviour

**Review by tonybaloney — APPROVED** [review]

**Pull request merged**
