### PR TITLE
Add failing Queue Listener Handler Test

### PR DESCRIPTION
**Pull request by Goldziher**
This PR adds a failing test to illustrate an issue with queue listener handler.

### CODE REVIEW

**Comment by Goldziher** [comment]
@microsoft-github-policy-service agree [company=n/a]

**Comment by Goldziher** [comment]
@microsoft-github-policy-service agree

**Comment by Goldziher** [comment]
@microsoft-github-policy-service agree

**Comment by tonybaloney** [comment]
Thanks for raising this, we'll take a look at the issue

**Pull request merged**
