### PR TITLE
Issue #101

### PR DESCRIPTION
**Pull request by Goldziher**
This is an update for issue #101, demonstrating that the test is well formed. It shouldn't be merged as such but only considered.

### CODE REVIEW

**Comment by pamelafox** [comment]
[Posting on both relevant PRs]
To keep our discussion in one place for now, let's keep discussing in https://github.com/microsoft/picologging/issues/90 and then figure out what code change to make.
Thank you!

**Comment by pamelafox** [comment]
I can verify that test_stdlib_logger passes for me and  test_picologger_logger fails for me.

However, I ran the code locally to try to understand the difference, and I see that both of them are logging to the handler's stream object:

```
>>> stdlib_logger = get_stdlib_logger("stdlib_test")
>>> stdlib_logger.info("Testing now!")
>>> stdlib_logger.handlers[0].listener.handlers[0].stream.getvalue()
'INFO - 2022-10-03 20:34:55,550 - stdlib_test - <stdin> - Testing now!\n'
```

```
>>> picologging_logger = get_picologging_logger("picologging_test")
>>> picologging_logger.info("Testing now!")
>>> picologging_logger.handlers[0].listener.handlers[0].stream.getvalue()
'Testing now!\n'
```

There does seem to be an issue that the logging module uses the formatter while the picologging module does not. That doesn't seem to be generally the case that formatter is ignored, as I tried a simpler example, so I think it's related to the nestedness/complexity of this setup.

As for why the picologging test fails, my hypothesis is that it's because your test uses pytest's caplog and caplog.at_level, which hook specifically into the logging library:
https://github.com/pytest-dev/pytest/blob/63d2f7f7f8ec8b09c4289f18a94178c520d93bff/src/_pytest/logging.py#L449
That fixture isn't capturing the picologging output.

**Comment by Goldziher** [comment]
> I can verify that test_stdlib_logger passes for me and test_picologger_logger fails for me.
> 
> However, I ran the code locally to try to understand the difference, and I see that both of them are logging to the handler's stream object:
> 
> ```
> >>> stdlib_logger = get_stdlib_logger("stdlib_test")
> >>> stdlib_logger.info("Testing now!")
> >>> stdlib_logger.handlers[0].listener.handlers[0].stream.getvalue()
> 'INFO - 2022-10-03 20:34:55,550 - stdlib_test - <stdin> - Testing now!\n'
> ```
> 
> ```
> >>> picologging_logger = get_picologging_logger("picologging_test")
> >>> picologging_logger.info("Testing now!")
> >>> picologging_logger.handlers[0].listener.handlers[0].stream.getvalue()
> 'Testing now!\n'
> ```
> 
> There does seem to be an issue that the logging module uses the formatter while the picologging module does not. That doesn't seem to be generally the case that formatter is ignored, as I tried a simpler example, so I think it's related to the nestedness/complexity of this setup.
> 
> As for why the picologging test fails, my hypothesis is that it's because your test uses pytest's caplog and caplog.at_level, which hook specifically into the logging library: https://github.com/pytest-dev/pytest/blob/63d2f7f7f8ec8b09c4289f18a94178c520d93bff/src/_pytest/logging.py#L449 That fixture isn't capturing the picologging output.

The issue is reproducible with the simple example i gave as well. Thus, I dont see the relation to complexity. As for pytest caplog - this might well be the case. If it is the issue though then it should be clarified in the docs that picologging cannot be tested with pytest, which is a fairly big problem I'd say, or a fix needs to be added. Additionally, I am using structlog as well, and that is actually working with caplog - while offering its own helper as well.

**Comment by pamelafox** [comment]
@Goldziher I am working on fixing a few issues that your test case demonstrated. One's in master, one's out for review, one more is pending.
 
As for the inability to use caplog, yes, I agree, that could certainly be added to limitations, given the popularity of pytest. I looked through your codebase for examples of caplog and structlog, but I think I only saw examples using structlog's custom helper. Can you point me to where you were able to use structlog with caplog? I'm curious how that worked. 

I haven't used structlog personally, so I'm still fuzzy as to how it integrates with core logging module. Based on the docs, I think it says there are options to use it alongside logging or standalone.

Thank you!

**Comment by Goldziher** [comment]
> @Goldziher I am working on fixing a few issues that your test case demonstrated. One's in master, one's out for review, one more is pending.
> 
> As for the inability to use caplog, yes, I agree, that could certainly be added to limitations, given the popularity of pytest. I looked through your codebase for examples of caplog and structlog, but I think I only saw examples using structlog's custom helper. Can you point me to where you were able to use structlog with caplog? I'm curious how that worked.
> 
> I haven't used structlog personally, so I'm still fuzzy as to how it integrates with core logging module. Based on the docs, I think it says there are options to use it alongside logging or standalone.
> 
> Thank you!

hI, cheers. I will have to check - will do after work today or tomorrow. Thanks for looking into this!

**Comment by pamelafox** [comment]
Per our other discussions, I'm closing this PR now. Thanks for helping us discover multiple issues!

**Pull request closed without merging**
